### ISSUE TITLE
Small Dependency Issues and Website Typos

### ISSUE THREAD

**Issue by sampollard** [flux-framework/flux-framework.github.io#22]
I was trying to build flux on Mac. Before I realized the futility of that, I came across some small errors while trying to satisfy dependencies. I'm referring to [this page](http://flux-framework.github.io/docs/requirements/).

Most of these are nit picking but there's a chance it would help someone who isn't installing on LC.

* You put a link to libmunge but when installing via macports or aptitude it's just referred to as munge.
* There's a small typo: libsod**ui**m --> libsodium
* in the configure script it says lua >= 5.1 but < 5.3 but the website says only lua 5.1
* jansson isn't listed as a dependency

This last one may be more proper to post in flux-core:
* libev included in flux is missing ev_kqueue.c. I got that file from [here](https://github.com/enki/libev/blob/master/ev_kqueue.c)

**Comment by SteVwonder** [comment]
We've removed the dependencies from the new site and pushed all of that to the individual repos and the docs. Closing.
