### ISSUE TITLE
Create a lighter logo

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-framework.github.io#40]
Would be nice to have a lighter logo that we can put on dark backgrounds.

**Comment by grondo** [comment]
We do have [flux-logo-v2-light.svg](https://github.com/flux-framework/flux-framework.github.io/blob/master/assets/flux-logo-v2-light.svg)

Do you mean the whole logo?

**Comment by SteVwonder** [comment]
I forgot we had that logo.  Thanks for the pointer.

> Do you mean the whole logo?

Yeah, I think that would still be good.

**Comment by grondo** [comment]
![logo](https://user-images.githubusercontent.com/741970/80621427-209ac800-89fc-11ea-8178-b6c0a126f515.png)

I found with the full logo if the field lines and the "flux" text were the same color like in the 'f' logo, then it was unreadable. How about this?

**Comment by SteVwonder** [comment]
Awesome!  :shipit:

(for anyone unfamiliar wondering why I posted a squirrel, that is the [ship it squirrel](https://www.quora.com/On-GitHub-what-is-the-significance-of-the-Ship-It-squirrel?share=1))
