### ISSUE TITLE
Add release notes from flux-accounting

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-framework.github.io#47]
The release notes generator script is not able to find the tagger/date information for the flux-accounting releases.  I suspect this is due to the use of lightweight vs annotated tags.  It does produce mostly the correct markdown, only the date is missing from the file contents and the file name.  If someone is willing to manually add the dates to releases 0.1.0->0.8.0, we can add those.  And going forward, I think flux-accounting can use annotated tags to enable the script to work automatically.

**Comment by cmoussa1** [comment]
I can care of this - sorry for not using annotated tags before! 

Can you let me know where I am supposed to add the dates to releases 0.1.0 -> 0.8.0? Is it on the GitHub website? Or maybe somewhere else?

**Comment by SteVwonder** [comment]
Not a problem!  If you run [this script](https://github.com/flux-framework/flux-framework.github.io/blob/master/src/gen-release-post.sh), it will generate a markdown file for each release.  The date needs to go in both the file name and in the metadata header at the top of the file.  [Here is an example file](https://github.com/flux-framework/flux-framework.github.io/blob/master/_posts/2021-04-22-flux-core-0.26.0.md).

Also for reference, here is how I ran the script for flux-accounting before I discovered the issue:
```bash
for x in $(seq 1 8); do ./src/gen-release-post.sh 0.$x.0 flux-accounting /tmp/flux-accounting-releasenotes; done
```

Once all of that is done, you can test out that the posts are generated on the new site correctly by running:
```
jekyll serve
```

There are also installation instructions for Jekyll on their site:

- https://jekyllrb.com/docs/#instructions
- https://jekyllrb.com/docs/installation/macos/
